# PPHS flats considerations

## Objective
The purpose of this notebook is to generate sufficient data to rank the PPHS flats available as of August 2024 from best to the worst, based on the following criteria:
1. Travel time to nearest MRT (lower = better)
2. Travel time to Raffles Place MRT (lower = better)
3. Cost of rental (lower = better)
4. Months to expiry (higher = better)

## Method
The original data collected will be from HDB's website for [flats available](https://www.hdb.gov.sg/cs/infoweb/residential/renting-a-flat/renting-from-hdb/parenthood-provisional-housing-schemepphs/application-procedure/flats-available-for-application-) and [rental rates](https://www.hdb.gov.sg/cs/infoweb/residential/renting-a-flat/renting-from-hdb/parenthood-provisional-housing-schemepphs/rents-and-deposits). 
The data will be tabulated in an excel sheet and processed with this notebook.

## Data Pre-processing

### Generating flats_available.xlsx
Before importing the data as a pandas dataframe, some pre-processing has to be done on Excel. Follow the steps below:

1. Go to [flats available](https://www.hdb.gov.sg/cs/infoweb/residential/renting-a-flat/renting-from-hdb/parenthood-provisional-housing-schemepphs/application-procedure/flats-available-for-application-) on the HDB site, select the entire table, copy and paste into Excel. Save it as `flats_available.xlsx `under raw data
1. Adjust the first column to `town`	`address`	`2room`	`3room`	`4room`	`site_expiry`
1. For rows sharing the same town, since in the table they were merged, adjust them accordingly so that the columns correspond properly. Your table should now look like this:
    ![formatted table](images/formatted_table.png)
1. Duplicate the towns down to those empty cells, and correct any formatting issues in Excel if needed.
1. Excel formulas to get the site expiry:
    1. Label Cell G1 as `site_exp_date`. In Cell G2, insert the formula 
        ```
        =DATE(RIGHT(F2,4),LEFT(F2,1)*3,1)
        ```
        Autofill the cells all the way down
        
    1. Label Cell H1 as `months_to_expiry`. In Cell H2, insert the formula
        ```
        =DATEDIF(TODAY(),G2,"m")
        ```
        Autofill the cells all the way down
    1. Fix any issues with error cells due to column F not being formatted properly. Once done, your table should look like this
        ![site expiry fixed](images/site_expiry_fixed.png)
1. You are now done with using Excel for pre-processing. Continue forth in this notebook

In [26]:
import pandas as pd

df = pd.read_excel("raw data/flats_available.xlsx")
df

,town,address,2room,3room,4room,site_expiry,site_exp_date,months_to_expiry
0,Ang Mo Kio,Blk 629 Ang Mo Kio Avenue 4,-,1,-,1Q 2030,2030-03-01,64
1,Bedok,Blk 13 Bedok South Road,3,-,-,4Q 2027,2027-12-01,37
2,Bedok,Blk 113 Bedok North Street 2,1,-,-,4Q 2027,2027-12-01,37
3,Bishan,Blk 410 Sin Ming Avenue,9,-,-,4Q 2027,2027-12-01,37
4,Bukit Batok,Blk 435A Bukit Batok West Avenue 5,6,-,-,1Q 2030,2030-03-01,64
5,Bukit Batok,Blk 447A Bukit Batok West Avenue 9,2,-,-,4Q 2027,2027-12-01,37
6,Bukit Merah,Blk 1 Tiong Bahru Road,-,2,7,4Q 2026,2026-12-01,25
7,Bukit Merah,Blk 3 Tiong Bahru Road,-,4,5,4Q2027,2027-12-01,37
8,Bukit Merah,Blk 5 Tiong Bahru Road,-,2,5,4Q 2027,2027-12-01,37
9,Bukit Merah,Blk 7 Tiong Bahru Road,-,1,1,4Q 2027,2027-12-01,37
10,Bukit Merah,Blk 9 Tiong Bahru Road,-,-,3,4Q 2027,2027-12-01,37
11,Bukit Merah,Blk 31 Telok Blangah Rise,-,2,-,1Q 2030,2030-03-01,64
12,Bukit Merah,Blk 55 Lengkok Bahru,-,1,-,1Q 2030,2030-03-01,64
13,Bukit Merah,Blk 110 Jalan Bukit Merah,-,1,-,1Q 2030,2030-03-01,64
14,Bukit Merah,Blk 115 Jalan Bukit Merah,-,1,-,1Q 2030,2030-03-01,64
15,Bukit Merah,Blk 116 Jalan Bukit Merah,-,1,-,1Q 2030,2030-03-01,64
16,Bukit Merah,Blk 121 Bukit Merah Lane 1,-,1,-,1Q 2030,2030-03-01,64
17,Choa Chu Kang,Blk 9 Teck Whye Lane,9,-,-,4Q 2027,2027-12-01,37
18,Choa Chu Kang,Blk 813A Choa Chu Kang Avenue 7,2,-,-,1Q 2030,2030-03-01,64
19,Hougang,Blk 313 Hougang Avenue 5,-,6,-,1Q 2030,2030-03-01,64
20,Jurong West,Blk 189 Boon Lay Drive,-,13,-,1Q 2030,2030-03-01,64
21,Jurong West,Blk 190 Boon Lay Drive,-,11,-,1Q 2030,2030-03-01,64
22,Jurong West,Blk 967B Jurong West Street 93,1,-,-,4Q 2027,2027-12-01,37
23,Kallang/ Whampoa,Blk 1 Thomson Road,-,1,-,1Q 2030,2030-03-01,64
24,Marine Parade,Blk 52 Marine Terrace,1,-,-,4Q 2027,2027-12-01,37
25,Queenstown,Blk 4 Dover Road,2,-,-,4Q 2027,2027-12-01,37
26,Queenstown,Blk 70 Commonwealth Drive,-,1,-,1Q 2030,2030-03-01,64
27,Queenstown,Blk 83 Commonwealth Close,1,-,-,4Q 2027,2027-12-01,37
28,Sembawang,Blk 106A Canberra Street,1,-,-,1Q 2030,2030-03-01,64
29,Sembawang,Blk 462 Sembawang Drive,2,-,-,1Q 2030,2030-03-01,64
30,Sengkang,Blk 182 Rivervale Crescent,2,-,-,4Q 2027,2027-12-01,37
31,Toa Payoh,Blk 52 Lorong 6 Toa Payoh,4,-,-,4Q 2027,2027-12-01,37
32,Toa Payoh,Blk 63 Lorong 5 Toa Payoh,15,-,-,4Q 2027,2027-12-01,37
33,Woodlands,Blk 144 Woodlands Street 13,-,-,32,1Q 2030,2030-03-01,64
34,Woodlands,Blk 147 Woodlands Street 13,-,-,21,1Q 2030,2030-03-01,64
35,Woodlands,Blk 153 Woodlands Street 13,-,-,4,1Q 2030,2030-03-01,64
36,Woodlands,Blk 693D Woodlands Avenue 6,2,-,-,1Q 2030,2030-03-01,64
37,Woodlands,Blk 785A Woodlands Rise,7,-,-,1Q 2030,2030-03-01,64
38,Yishun,Blk 108 Yishun Ring Road,-,1,-,1Q 2030,2030-03-01,64
39,Yishun,Blk 510A Yishun Street 51,1,-,-,1Q 2030,2030-03-01,64
40,Yishun,Blk 510B Yishun Street 51,1,-,-,4Q 2027,2027-12-01,37

In [27]:
# Strip all text
df = df.applymap(lambda x: x.strip() if isinstance(x, str) else x)

# Replace all null values with 0
df.replace(['-', 'NaN', 'nan'], 0, inplace=True)

# Make these columns integers
df['2room'] = df['2room'].apply(lambda x: int(x))
df['3room'] = df['3room'].apply(lambda x: int(x))
df['4room'] = df['4room'].apply(lambda x: int(x))
df.head()

,town,address,2room,3room,4room,site_expiry,site_exp_date,months_to_expiry
0,Ang Mo Kio,Blk 629 Ang Mo Kio Avenue 4,0,1,0,1Q 2030,2030-03-01,64
1,Bedok,Blk 13 Bedok South Road,3,0,0,4Q 2027,2027-12-01,37
2,Bedok,Blk 113 Bedok North Street 2,1,0,0,4Q 2027,2027-12-01,37
3,Bishan,Blk 410 Sin Ming Avenue,9,0,0,4Q 2027,2027-12-01,37
4,Bukit Batok,Blk 435A Bukit Batok West Avenue 5,6,0,0,1Q 2030,2030-03-01,64

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41 entries, 0 to 40
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   town              41 non-null     object
 1   address           41 non-null     object
 2   2room             41 non-null     int64
 3   3room             41 non-null     int64
 4   4room             41 non-null     int64
 5   site_expiry       41 non-null     object
 6   site_exp_date     41 non-null     datetime64[ns]
 7   months_to_expiry  41 non-null     int64
dtypes: datetime64[ns](1), int64(4), object(3)
memory usage: 2.7+ KB

## Getting geospatial data from the OneMap API

This section uses the free OneMap API to generate the postal code, lat, and long from the address as the search key

In [29]:
import requests
import time

def get_geodata(address: str) -> tuple:
    '''
    returns (postal, lat, long)
    '''
    if address is None:
        return (0,0,0)
    else:
        url = f"https://www.onemap.gov.sg/api/common/elastic/search?searchVal={address}&returnGeom=Y&getAddrDetails=Y"   
        response = requests.request("GET", url).json()
        try:
            postal = response['results'][0]['POSTAL']
            lat = response['results'][0]['LATITUDE']
            long = response['results'][0]['LONGITUDE']
            time.sleep(0.5) # to not overwhelm the api
            return (postal,lat,long)
        except:
            try:
                # for some reason cannot have the "blk " at the front
                if address[:4].lower() == "blk ":
                    return get_geodata(address[4:])
                return (0,0,0)
            except:
                print(f"error {address}, {address[4:]}")
                return (0,0,0)

# Test on 1 sample point
get_geodata(df['address'][2])

('498775', '1.35046982429754', '103.967474078225')

In [30]:
df[['postal', 'latitude', 'longitude']] = df['address'].apply(lambda x: pd.Series(get_geodata(x)))
df

,town,address,2room,3room,4room,site_expiry,site_exp_date,months_to_expiry,postal,latitude,longitude
0,Ang Mo Kio,Blk 629 Ang Mo Kio Avenue 4,0,1,0,1Q 2030,2030-03-01,64,560641,1.37858940772641,103.840329743826
1,Bedok,Blk 13 Bedok South Road,3,0,0,4Q 2027,2027-12-01,37,463152,1.31871703752085,103.947012423053
2,Bedok,Blk 113 Bedok North Street 2,1,0,0,4Q 2027,2027-12-01,37,498775,1.35046982429754,103.967474078225
3,Bishan,Blk 410 Sin Ming Avenue,9,0,0,4Q 2027,2027-12-01,37,570444,1.35853942882943,103.832309279131
4,Bukit Batok,Blk 435A Bukit Batok West Avenue 5,6,0,0,1Q 2030,2030-03-01,64,659083,1.35861159094192,103.751790910733
5,Bukit Batok,Blk 447A Bukit Batok West Avenue 9,2,0,0,4Q 2027,2027-12-01,37,651469,1.35545061835629,103.742102913234
6,Bukit Merah,Blk 1 Tiong Bahru Road,0,2,7,4Q 2026,2026-12-01,25,159053,1.28736604092556,103.81481812521
7,Bukit Merah,Blk 3 Tiong Bahru Road,0,4,5,4Q2027,2027-12-01,37,159053,1.28736604092556,103.81481812521
8,Bukit Merah,Blk 5 Tiong Bahru Road,0,2,5,4Q 2027,2027-12-01,37,162005,1.28620043157708,103.831687678938
9,Bukit Merah,Blk 7 Tiong Bahru Road,0,1,1,4Q 2027,2027-12-01,37,161007,1.28613832025727,103.831069869517
10,Bukit Merah,Blk 9 Tiong Bahru Road,0,0,3,4Q 2027,2027-12-01,37,161009,1.28615970912446,103.830448149376
11,Bukit Merah,Blk 31 Telok Blangah Rise,0,2,0,1Q 2030,2030-03-01,64,090028,1.27394761788206,103.820866934319
12,Bukit Merah,Blk 55 Lengkok Bahru,0,1,0,1Q 2030,2030-03-01,64,NIL,1.32005980149776,103.871792121922
13,Bukit Merah,Blk 110 Jalan Bukit Merah,0,1,0,1Q 2030,2030-03-01,64,159840,1.2820403214522,103.817210058118
14,Bukit Merah,Blk 115 Jalan Bukit Merah,0,1,0,1Q 2030,2030-03-01,64,159840,1.2820403214522,103.817210058118
15,Bukit Merah,Blk 116 Jalan Bukit Merah,0,1,0,1Q 2030,2030-03-01,64,159840,1.2820403214522,103.817210058118
16,Bukit Merah,Blk 121 Bukit Merah Lane 1,0,1,0,1Q 2030,2030-03-01,64,151119,1.28593893475633,103.804715808324
17,Choa Chu Kang,Blk 9 Teck Whye Lane,9,0,0,4Q 2027,2027-12-01,37,680113,1.37805373450801,103.750693424497
18,Choa Chu Kang,Blk 813A Choa Chu Kang Avenue 7,2,0,0,1Q 2030,2030-03-01,64,NIL,1.37484413654311,103.746633780973
19,Hougang,Blk 313 Hougang Avenue 5,0,6,0,1Q 2030,2030-03-01,64,168874,1.27604839626377,103.82936381544
20,Jurong West,Blk 189 Boon Lay Drive,0,13,0,1Q 2030,2030-03-01,64,641268,1.3479800119286,103.707547320825
21,Jurong West,Blk 190 Boon Lay Drive,0,11,0,1Q 2030,2030-03-01,64,641268,1.3479800119286,103.707547320825
22,Jurong West,Blk 967B Jurong West Street 93,1,0,0,4Q 2027,2027-12-01,37,640993,1.33666121249097,103.693455495264
23,Kallang/ Whampoa,Blk 1 Thomson Road,0,1,0,1Q 2030,2030-03-01,64,298333,1.32862230231263,103.837652705219
24,Marine Parade,Blk 52 Marine Terrace,1,0,0,4Q 2027,2027-12-01,37,458537,1.30998637977856,103.92419284319
25,Queenstown,Blk 4 Dover Road,2,0,0,4Q 2027,2027-12-01,37,268857,1.31743915158967,103.807379214161
26,Queenstown,Blk 70 Commonwealth Drive,0,1,0,1Q 2030,2030-03-01,64,730501,1.43292523586445,103.792006999106
27,Queenstown,Blk 83 Commonwealth Close,1,0,0,4Q 2027,2027-12-01,37,NIL,1.36895143913237,103.773340678215
28,Sembawang,Blk 106A Canberra Street,1,0,0,1Q 2030,2030-03-01,64,179360,1.29360606337051,103.849526126465
29,Sembawang,Blk 462 Sembawang Drive,2,0,0,1Q 2030,2030-03-01,64,NIL,1.33598647881104,103.814300881432
30,Sengkang,Blk 182 Rivervale Crescent,2,0,0,4Q 2027,2027-12-01,37,140097,1.30616047214581,103.801495664171
31,Toa Payoh,Blk 52 Lorong 6 Toa Payoh,4,0,0,4Q 2027,2027-12-01,37,310190,1.33297850289872,103.848761042692
32,Toa Payoh,Blk 63 Lorong 5 Toa Payoh,15,0,0,4Q 2027,2027-12-01,37,319457,1.33311994430643,103.852368188626
33,Woodlands,Blk 144 Woodlands Street 13,0,0,32,1Q 2030,2030-03-01,64,730103,1.4366212320968,103.78097673981
34,Woodlands,Blk 147 Woodlands Street 13,0,0,21,1Q 2030,2030-03-01,64,730103,1.4366212320968,103.78097673981
35,Woodlands,Blk 153 Woodlands Street 13,0,0,4,1Q 2030,2030-03-01,64,730103,1.4366212320968,103.78097673981
36,Woodlands,Blk 693D Woodlands Avenue 6,2,0,0,1Q 2030,2030-03-01,64,639311,1.3257243474532,103.650088287095
37,Woodlands,Blk 785A Woodlands Rise,7,0,0,1Q 2030,2030-03-01,64,308143,1.31908636997896,103.847053580169
38,Yishun,Blk 108 Yishun Ring Road,0,1,0,1Q 2030,2030-03-01,64,768690,1.42961544508137,103.830029543751
39,Yishun,Blk 510A Yishun Street 51,1,0,0,1Q 2030,2030-03-01,64,510561,1.36701303042853,103.950865061907
40,Yishun,Blk 510B Yishun Street 51,1,0,0,4Q 2027,2027-12-01,37,510561,1.36701303042853,103.950865061907

At this point, you might get some 'NIL' fields for the postal code. This isn't really an issue since we won't be using it, but if it bugs you, you can go change it manually. OneMap a bit funky sometimes. 

If the function returns the lat long as 0, 0 however, manually adjust them or just run the function again until they populate the numbers properly.

## Getting the nearest MRT for each address
This section fuses the mrt_lrt_data.csv data that I churned from a previous project. It calculates the nearest MRT to each address.

In [31]:
mrt_df = pd.read_csv("raw data/mrt_lrt_data.csv")
mrt_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   station_name  157 non-null    object
 1   type          157 non-null    object
 2   lat           157 non-null    float64
 3   lng           157 non-null    float64
dtypes: float64(2), object(2)
memory usage: 5.0+ KB

In [32]:
# Filter out only the nearest MRT. I don't really care about LRTs 
mrt_df = mrt_df[mrt_df['type'] == "MRT"]
mrt_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 119 entries, 0 to 118
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   station_name  119 non-null    object
 1   type          119 non-null    object
 2   lat           119 non-null    float64
 3   lng           119 non-null    float64
dtypes: float64(2), object(2)
memory usage: 4.6+ KB

In [33]:
from geopy.distance import geodesic

# Define a new function to be applied for faster computation
def find_nearest_mrt(row):
    '''
    function that takes in the rows, and returns the nearest MRT station and the distance to it in km
    '''
    min_distance = float('inf')
    nearest_mrt = ''
    
    for idx, mrt in mrt_df.iterrows():
        distance = geodesic((row['latitude'], row['longitude']), (mrt['lat'], mrt['lng'])).km
        
        if distance < min_distance:
            min_distance = distance
            nearest_mrt = mrt['station_name']
    
    return pd.Series({'nearest MRT': nearest_mrt, 'distance to nearest MRT': min_distance})

df[['nearest_MRT', 'distance_to_nearest_MRT']] = df.apply(find_nearest_mrt, axis=1)
df.head()

,town,address,2room,3room,4room,site_expiry,site_exp_date,months_to_expiry,postal,latitude,longitude,nearest_MRT,distance_to_nearest_MRT
0,Ang Mo Kio,Blk 629 Ang Mo Kio Avenue 4,0,1,0,1Q 2030,2030-03-01,64,560641,1.37858940772641,103.840329743826,Yio Chu Kang,0.620158
1,Bedok,Blk 13 Bedok South Road,3,0,0,4Q 2027,2027-12-01,37,463152,1.31871703752085,103.947012423053,Tanah Merah,0.951908
2,Bedok,Blk 113 Bedok North Street 2,1,0,0,4Q 2027,2027-12-01,37,498775,1.35046982429754,103.967474078225,Upper Changi,1.128645
3,Bishan,Blk 410 Sin Ming Avenue,9,0,0,4Q 2027,2027-12-01,37,570444,1.35853942882943,103.832309279131,Marymount,1.290661
4,Bukit Batok,Blk 435A Bukit Batok West Avenue 5,6,0,0,1Q 2030,2030-03-01,64,659083,1.35861159094192,103.751790910733,Bukit Gombak,0.048373

## Getting the travel times for each address

This section uses the OneMap API (this section requires you to get a token from them, which is free) to generate the travel times from each address to the target location. To get the OneMap API, visit https://www.onemap.gov.sg/apidocs/register to register for an API token. Save it to your keys.py as your_onemap_token.

In [34]:
import keys

def get_mrt_travel_time(start_lat, start_long, nearest_mrt) -> int:
    '''
    this function takes in the start lat long, and the destination MRT Station
    returns the duration in minutes
    '''
    date = '06-06-2024'
    x, end_lat, end_long = get_geodata(f"{nearest_mrt} MRT Station")
    
    url = f"https://www.onemap.gov.sg/api/public/routingsvc/route?start={start_lat}%2C{start_long}&end={end_lat}%2C{end_long}&routeType=pt&date={date}&time=12%3A35%3A00&mode=TRANSIT&maxWalkDistance=400&numItineraries=1"
        
    headers = {"Authorization": keys.your_onemap_token}
        
    response = requests.request("GET", url, headers=headers).json()
    try:
        duration = response['plan']['itineraries'][0]['duration']/60
        return duration
    except:
        return None
   
# Test on 1 sample point
i=6
get_mrt_travel_time(df['latitude'][i], df['longitude'][i], df['nearest_MRT'][i])

11.216666666666667

In [35]:
df['time_to_MRT'] = df.apply(lambda row: get_mrt_travel_time(row['latitude'], row['longitude'], f"{row['nearest_MRT']}"), axis=1)
df.head()

,town,address,2room,3room,4room,site_expiry,site_exp_date,months_to_expiry,postal,latitude,longitude,nearest_MRT,distance_to_nearest_MRT,time_to_MRT
0,Ang Mo Kio,Blk 629 Ang Mo Kio Avenue 4,0,1,0,1Q 2030,2030-03-01,64,560641,1.37858940772641,103.840329743826,Yio Chu Kang,0.620158,13.466667
1,Bedok,Blk 13 Bedok South Road,3,0,0,4Q 2027,2027-12-01,37,463152,1.31871703752085,103.947012423053,Tanah Merah,0.951908,18.466667
2,Bedok,Blk 113 Bedok North Street 2,1,0,0,4Q 2027,2027-12-01,37,498775,1.35046982429754,103.967474078225,Upper Changi,1.128645,17.650000
3,Bishan,Blk 410 Sin Ming Avenue,9,0,0,4Q 2027,2027-12-01,37,570444,1.35853942882943,103.832309279131,Marymount,1.290661,27.333333
4,Bukit Batok,Blk 435A Bukit Batok West Avenue 5,6,0,0,1Q 2030,2030-03-01,64,659083,1.35861159094192,103.751790910733,Bukit Gombak,0.048373,NaN

In [36]:
# Generate the travel time to Raffles Place MRT Station (had some issues with City Hall MRT for some reason; API was returning 71min for Dakota to City Hall)
df['time_to_RP'] = df.apply(lambda row: get_mrt_travel_time(row['latitude'], row['longitude'], "Raffles Place"), axis=1)
df

,town,address,2room,3room,4room,site_expiry,site_exp_date,months_to_expiry,postal,latitude,longitude,nearest_MRT,distance_to_nearest_MRT,time_to_MRT,time_to_RP
0,Ang Mo Kio,Blk 629 Ang Mo Kio Avenue 4,0,1,0,1Q 2030,2030-03-01,64,560641,1.37858940772641,103.840329743826,Yio Chu Kang,0.620158,13.466667,36.883333
1,Bedok,Blk 13 Bedok South Road,3,0,0,4Q 2027,2027-12-01,37,463152,1.31871703752085,103.947012423053,Tanah Merah,0.951908,18.466667,38.850000
2,Bedok,Blk 113 Bedok North Street 2,1,0,0,4Q 2027,2027-12-01,37,498775,1.35046982429754,103.967474078225,Upper Changi,1.128645,17.650000,51.850000
3,Bishan,Blk 410 Sin Ming Avenue,9,0,0,4Q 2027,2027-12-01,37,570444,1.35853942882943,103.832309279131,Marymount,1.290661,27.333333,36.866667
4,Bukit Batok,Blk 435A Bukit Batok West Avenue 5,6,0,0,1Q 2030,2030-03-01,64,659083,1.35861159094192,103.751790910733,Bukit Gombak,0.048373,NaN,34.916667
5,Bukit Batok,Blk 447A Bukit Batok West Avenue 9,2,0,0,4Q 2027,2027-12-01,37,651469,1.35545061835629,103.742102913234,Bukit Batok,1.092392,19.366667,46.150000
6,Bukit Merah,Blk 1 Tiong Bahru Road,0,2,7,4Q 2026,2026-12-01,25,159053,1.28736604092556,103.81481812521,Redhill,0.336365,11.216667,18.850000
7,Bukit Merah,Blk 3 Tiong Bahru Road,0,4,5,4Q2027,2027-12-01,37,159053,1.28736604092556,103.81481812521,Redhill,0.336365,11.216667,18.850000
8,Bukit Merah,Blk 5 Tiong Bahru Road,0,2,5,4Q 2027,2027-12-01,37,162005,1.28620043157708,103.831687678938,Tiong Bahru,0.528054,8.133333,11.833333
9,Bukit Merah,Blk 7 Tiong Bahru Road,0,1,1,4Q 2027,2027-12-01,37,161007,1.28613832025727,103.831069869517,Tiong Bahru,0.460152,7.116667,13.850000
10,Bukit Merah,Blk 9 Tiong Bahru Road,0,0,3,4Q 2027,2027-12-01,37,161009,1.28615970912446,103.830448149376,Tiong Bahru,0.391097,5.916667,12.650000
11,Bukit Merah,Blk 31 Telok Blangah Rise,0,2,0,1Q 2030,2030-03-01,64,090028,1.27394761788206,103.820866934319,HarbourFront,0.940112,20.750000,21.183333
12,Bukit Merah,Blk 55 Lengkok Bahru,0,1,0,1Q 2030,2030-03-01,64,NIL,1.32005980149776,103.871792121922,Geylang Bahru,0.161299,3.300000,22.333333
13,Bukit Merah,Blk 110 Jalan Bukit Merah,0,1,0,1Q 2030,2030-03-01,64,159840,1.2820403214522,103.817210058118,Redhill,0.845405,15.766667,15.266667
14,Bukit Merah,Blk 115 Jalan Bukit Merah,0,1,0,1Q 2030,2030-03-01,64,159840,1.2820403214522,103.817210058118,Redhill,0.845405,15.766667,15.266667
15,Bukit Merah,Blk 116 Jalan Bukit Merah,0,1,0,1Q 2030,2030-03-01,64,159840,1.2820403214522,103.817210058118,Redhill,0.845405,15.766667,15.266667
16,Bukit Merah,Blk 121 Bukit Merah Lane 1,0,1,0,1Q 2030,2030-03-01,64,151119,1.28593893475633,103.804715808324,Queenstown,0.996007,18.316667,21.766667
17,Choa Chu Kang,Blk 9 Teck Whye Lane,9,0,0,4Q 2027,2027-12-01,37,680113,1.37805373450801,103.750693424497,Choa Chu Kang,1.080102,20.883333,47.716667
18,Choa Chu Kang,Blk 813A Choa Chu Kang Avenue 7,2,0,0,1Q 2030,2030-03-01,64,NIL,1.37484413654311,103.746633780973,Choa Chu Kang,1.197210,23.483333,55.183333
19,Hougang,Blk 313 Hougang Avenue 5,0,6,0,1Q 2030,2030-03-01,64,168874,1.27604839626377,103.82936381544,Tiong Bahru,1.192270,26.200000,18.016667
20,Jurong West,Blk 189 Boon Lay Drive,0,13,0,1Q 2030,2030-03-01,64,641268,1.3479800119286,103.707547320825,Boon Lay,1.052744,22.683333,49.116667
21,Jurong West,Blk 190 Boon Lay Drive,0,11,0,1Q 2030,2030-03-01,64,641268,1.3479800119286,103.707547320825,Boon Lay,1.052744,22.683333,49.116667
22,Jurong West,Blk 967B Jurong West Street 93,1,0,0,4Q 2027,2027-12-01,37,640993,1.33666121249097,103.693455495264,Pioneer,0.454420,7.183333,41.483333
23,Kallang/ Whampoa,Blk 1 Thomson Road,0,1,0,1Q 2030,2030-03-01,64,298333,1.32862230231263,103.837652705219,Caldecott,1.022023,22.583333,26.666667
24,Marine Parade,Blk 52 Marine Terrace,1,0,0,4Q 2027,2027-12-01,37,458537,1.30998637977856,103.92419284319,Bedok,1.692207,18.366667,39.616667
25,Queenstown,Blk 4 Dover Road,2,0,0,4Q 2027,2027-12-01,37,268857,1.31743915158967,103.807379214161,Farrer Road,0.041277,NaN,23.600000
26,Queenstown,Blk 70 Commonwealth Drive,0,1,0,1Q 2030,2030-03-01,64,730501,1.43292523586445,103.792006999106,Woodlands,0.768069,16.066667,58.766667
27,Queenstown,Blk 83 Commonwealth Close,1,0,0,4Q 2027,2027-12-01,37,NIL,1.36895143913237,103.773340678215,Hillview,0.920831,22.500000,55.366667
28,Sembawang,Blk 106A Canberra Street,1,0,0,1Q 2030,2030-03-01,64,179360,1.29360606337051,103.849526126465,City Hall,0.290266,7.550000,24.983333
29,Sembawang,Blk 462 Sembawang Drive,2,0,0,1Q 2030,2030-03-01,64,NIL,1.33598647881104,103.814300881432,Tan Kah Kee,1.326790,20.900000,43.183333
30,Sengkang,Blk 182 Rivervale Crescent,2,0,0,4Q 2027,2027-12-01,37,140097,1.30616047214581,103.801495664171,Commonwealth,0.542005,11.500000,22.900000
31,Toa Payoh,Blk 52 Lorong 6 Toa Payoh,4,0,0,4Q 2027,2027-12-01,37,310190,1.33297850289872,103.848761042692,Toa Payoh,0.160521,3.066667,16.583333
32,Toa Payoh,Blk 63 Lorong 5 Toa Payoh,15,0,0,4Q 2027,2027-12-01,37,319457,1.33311994430643,103.852368188626,Toa Payoh,0.554565,12.633333,23.966667
33,Woodlands,Blk 144 Woodlands Street 13,0,0,32,1Q 2030,2030-03-01,64,730103,1.4366212320968,103.78097673981,Woodlands,0.605524,11.833333,54.766667
34,Woodlands,Blk 147 Woodlands Street 13,0,0,21,1Q 2030,2030-03-01,64,730103,1.4366212320968,103.78097673981,Woodlands,0.605524,11.833333,54.766667
35,Woodlands,Blk 153 Woodlands Street 13,0,0,4,1Q 2030,2030-03-01,64,730103,1.4366212320968,103.78097673981,Woodlands,0.605524,11.833333,54.766667
36,Woodlands,Blk 693D Woodlands Avenue 6,2,0,0,1Q 2030,2030-03-01,64,639311,1.3257243474532,103.650088287095,Tuas Crescent,0.524596,15.433333,55.616667
37,Woodlands,Blk 785A Woodlands Rise,7,0,0,1Q 2030,2030-03-01,64,308143,1.31908636997896,103.847053580169,Novena,0.420914,8.550000,18.750000
38,Yishun,Blk 108 Yishun Ring Road,0,1,0,1Q 2030,2030-03-01,64,768690,1.42961544508137,103.830029543751,Yishun,0.558062,10.283333,42.366667
39,Yishun,Blk 510A Yishun Street 51,1,0,0,1Q 2030,2030-03-01,64,510561,1.36701303042853,103.950865061907,Pasir Ris,0.708432,13.600000,46.666667
40,Yishun,Blk 510B Yishun Street 51,1,0,0,4Q 2027,2027-12-01,37,510561,1.36701303042853,103.950865061907,Pasir Ris,0.708432,13.600000,46.666667

## Getting the rental prices for each property
This section generates the final PPHS Summary dataset by picking the relevant features for analysis. To get the rental rates, I split up each address to the unit types available, and matched it with the rental rates listed on the HDB website

In [37]:
# For towns like Kallang / Whampoa, keep only Kallang
df['town'] = df['town'].apply(lambda x : x.split('/')[0])
df.head()

,town,address,2room,3room,4room,site_expiry,site_exp_date,months_to_expiry,postal,latitude,longitude,nearest_MRT,distance_to_nearest_MRT,time_to_MRT,time_to_RP
0,Ang Mo Kio,Blk 629 Ang Mo Kio Avenue 4,0,1,0,1Q 2030,2030-03-01,64,560641,1.37858940772641,103.840329743826,Yio Chu Kang,0.620158,13.466667,36.883333
1,Bedok,Blk 13 Bedok South Road,3,0,0,4Q 2027,2027-12-01,37,463152,1.31871703752085,103.947012423053,Tanah Merah,0.951908,18.466667,38.850000
2,Bedok,Blk 113 Bedok North Street 2,1,0,0,4Q 2027,2027-12-01,37,498775,1.35046982429754,103.967474078225,Upper Changi,1.128645,17.650000,51.850000
3,Bishan,Blk 410 Sin Ming Avenue,9,0,0,4Q 2027,2027-12-01,37,570444,1.35853942882943,103.832309279131,Marymount,1.290661,27.333333,36.866667
4,Bukit Batok,Blk 435A Bukit Batok West Avenue 5,6,0,0,1Q 2030,2030-03-01,64,659083,1.35861159094192,103.751790910733,Bukit Gombak,0.048373,NaN,34.916667

In [38]:
# Get the rental rates data from csv
rental_rates_df = pd.read_csv('processed data/rental_rates.csv')

# Function to get the rental rate 
def get_rental_rate(town, rooms):
    if isinstance(rooms,str) and "room" in rooms:
        rooms = int(rooms[0])
    try:
        # Match the town and room type to get the price
        return rental_rates_df[rental_rates_df['town']==town][f'{rooms}room'].values[0]
    except:
        # Some towns may experience errors, requires manual correction
        return 0

# Test on 1 sample point
get_rental_rate('Ang Mo Kio', 2)

500

In [39]:
df = df.fillna(0)

In [40]:
# Create an empty list to store the rows
rows = []

# Iterate through each row in the DataFrame
for index, row in df.iterrows():
    town = row['town']
    for room_type in ['2room', '3room', '4room']:
        if row[room_type] != 0:  # Filter out rows with 0 values
            rows.append({'town': town, 'rooms': int(room_type.strip('room')), # Creating a new dataframe with these columns
                         'address': row['address'],
                         'nearest_MRT': row['nearest_MRT'],
                         'time_to_MRT': int(round(row['time_to_MRT'], 0)),   # criteria 1
                         'time_to_RP': int(round(row['time_to_RP'], 0)),     # criteria 2
                         'rent': get_rental_rate(town, room_type),           # criteria 3
                         'site_expiry': row['site_expiry'],
                         'months_to_expiry': row['months_to_expiry'],        # criteria 4
                         'availability': row[room_type]
                         })

# Create a new DataFrame from the list of rows
PPHS_summary_df = pd.DataFrame(rows)
PPHS_summary_df

,town,rooms,address,nearest_MRT,time_to_MRT,time_to_RP,rent,site_expiry,months_to_expiry,availability
0,Ang Mo Kio,3,Blk 629 Ang Mo Kio Avenue 4,Yio Chu Kang,13,37,800,1Q 2030,64,1
1,Bedok,2,Blk 13 Bedok South Road,Tanah Merah,18,39,500,4Q 2027,37,3
2,Bedok,2,Blk 113 Bedok North Street 2,Upper Changi,18,52,500,4Q 2027,37,1
3,Bishan,2,Blk 410 Sin Ming Avenue,Marymount,27,37,0,4Q 2027,37,9
4,Bukit Batok,2,Blk 435A Bukit Batok West Avenue 5,Bukit Gombak,0,35,500,1Q 2030,64,6
5,Bukit Batok,2,Blk 447A Bukit Batok West Avenue 9,Bukit Batok,19,46,500,4Q 2027,37,2
6,Bukit Merah,3,Blk 1 Tiong Bahru Road,Redhill,11,19,700,4Q 2026,25,2
7,Bukit Merah,4,Blk 1 Tiong Bahru Road,Redhill,11,19,1500,4Q 2026,25,7
8,Bukit Merah,3,Blk 3 Tiong Bahru Road,Redhill,11,19,700,4Q2027,37,4
9,Bukit Merah,4,Blk 3 Tiong Bahru Road,Redhill,11,19,1500,4Q2027,37,5
10,Bukit Merah,3,Blk 5 Tiong Bahru Road,Tiong Bahru,8,12,700,4Q 2027,37,2
11,Bukit Merah,4,Blk 5 Tiong Bahru Road,Tiong Bahru,8,12,1500,4Q 2027,37,5
12,Bukit Merah,3,Blk 7 Tiong Bahru Road,Tiong Bahru,7,14,700,4Q 2027,37,1
13,Bukit Merah,4,Blk 7 Tiong Bahru Road,Tiong Bahru,7,14,1500,4Q 2027,37,1
14,Bukit Merah,4,Blk 9 Tiong Bahru Road,Tiong Bahru,6,13,1500,4Q 2027,37,3
15,Bukit Merah,3,Blk 31 Telok Blangah Rise,HarbourFront,21,21,700,1Q 2030,64,2
16,Bukit Merah,3,Blk 55 Lengkok Bahru,Geylang Bahru,3,22,700,1Q 2030,64,1
17,Bukit Merah,3,Blk 110 Jalan Bukit Merah,Redhill,16,15,700,1Q 2030,64,1
18,Bukit Merah,3,Blk 115 Jalan Bukit Merah,Redhill,16,15,700,1Q 2030,64,1
19,Bukit Merah,3,Blk 116 Jalan Bukit Merah,Redhill,16,15,700,1Q 2030,64,1
20,Bukit Merah,3,Blk 121 Bukit Merah Lane 1,Queenstown,18,22,700,1Q 2030,64,1
21,Choa Chu Kang,2,Blk 9 Teck Whye Lane,Choa Chu Kang,21,48,400,4Q 2027,37,9
22,Choa Chu Kang,2,Blk 813A Choa Chu Kang Avenue 7,Choa Chu Kang,23,55,400,1Q 2030,64,2
23,Hougang,3,Blk 313 Hougang Avenue 5,Tiong Bahru,26,18,700,1Q 2030,64,6
24,Jurong West,3,Blk 189 Boon Lay Drive,Boon Lay,23,49,700,1Q 2030,64,13
25,Jurong West,3,Blk 190 Boon Lay Drive,Boon Lay,23,49,700,1Q 2030,64,11
26,Jurong West,2,Blk 967B Jurong West Street 93,Pioneer,7,41,500,4Q 2027,37,1
27,Kallang,3,Blk 1 Thomson Road,Caldecott,23,27,800,1Q 2030,64,1
28,Marine Parade,2,Blk 52 Marine Terrace,Bedok,18,40,550,4Q 2027,37,1
29,Queenstown,2,Blk 4 Dover Road,Farrer Road,0,24,550,4Q 2027,37,2
30,Queenstown,3,Blk 70 Commonwealth Drive,Woodlands,16,59,800,1Q 2030,64,1
31,Queenstown,2,Blk 83 Commonwealth Close,Hillview,22,55,550,4Q 2027,37,1
32,Sembawang,2,Blk 106A Canberra Street,City Hall,8,25,400,1Q 2030,64,1
33,Sembawang,2,Blk 462 Sembawang Drive,Tan Kah Kee,21,43,400,1Q 2030,64,2
34,Sengkang,2,Blk 182 Rivervale Crescent,Commonwealth,12,23,400,4Q 2027,37,2
35,Toa Payoh,2,Blk 52 Lorong 6 Toa Payoh,Toa Payoh,3,17,550,4Q 2027,37,4
36,Toa Payoh,2,Blk 63 Lorong 5 Toa Payoh,Toa Payoh,13,24,550,4Q 2027,37,15
37,Woodlands,4,Blk 144 Woodlands Street 13,Woodlands,12,55,800,1Q 2030,64,32
38,Woodlands,4,Blk 147 Woodlands Street 13,Woodlands,12,55,800,1Q 2030,64,21
39,Woodlands,4,Blk 153 Woodlands Street 13,Woodlands,12,55,800,1Q 2030,64,4
40,Woodlands,2,Blk 693D Woodlands Avenue 6,Tuas Crescent,15,56,400,1Q 2030,64,2
41,Woodlands,2,Blk 785A Woodlands Rise,Novena,9,19,400,1Q 2030,64,7
42,Yishun,3,Blk 108 Yishun Ring Road,Yishun,10,42,700,1Q 2030,64,1
43,Yishun,2,Blk 510A Yishun Street 51,Pasir Ris,14,47,500,1Q 2030,64,1
44,Yishun,2,Blk 510B Yishun Street 51,Pasir Ris,14,47,500,4Q 2027,37,1

## Fixing incorrect values

This is the frustrating part about OneMap's API. It returns junk sometimes and I can't seem to generate consistent results. Running the same cells at different times literally produces different results, so at this point you might have to come in to manually edit some stuff.

## Export output as xlsx
The data generation works has been completed. I will now analyse the data in Excel instead as it is more versatile and intuitive for my needs

In [41]:
PPHS_summary_df.to_excel('processed data/PPHS Summary.xlsx', index=False)